name: Publish Image

on:
  push:
    tags:
      - '*'

jobs:
  push-image:
    name: Build and Push
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_REGISTRY: ghcr.io/${{github.actor}}/libreoffice-headless
      DOCKER_IMAGE_TAG: ${{github.ref_name}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build and push'
        run: |
          export DOCKER_IMAGE_REGISTRY
          export DOCKER_IMAGE_TAG
          make all